import sys; sys.path += [".."]
from mms.api import API

api = API("evp_strain_7079")
api.read_data("evp_strain_7079.csv")

api.add_input("evp_s0", ["log", "linear"])
api.add_input("evp_R", ["log", "linear"])
api.add_input("evp_d", ["log", "linear"])
api.add_input("evp_n", ["log", "linear"])
api.add_input("evp_eta", ["log", "linear"])

api.add_output("x_end", ["log", "linear"])
api.add_output("y_1", ["log", "linear"])
api.add_output("y_2", ["log", "linear"])
api.add_output("y_3", ["log", "linear"])
api.add_output("y_4", ["log", "linear"])
api.add_output("y_5", ["log", "linear"])
api.add_output("y_6", ["log", "linear"])
api.add_output("y_7", ["log", "linear"])
api.add_output("y_8", ["log", "linear"])
api.add_output("y_9", ["log", "linear"])
api.add_output("y_10", ["log", "linear"])
api.add_output("y_11", ["log", "linear"])
api.add_output("y_12", ["log", "linear"])
api.add_output("y_13", ["log", "linear"])
api.add_output("y_14", ["log", "linear"])
api.add_output("y_15", ["log", "linear"])
api.add_output("y_16", ["log", "linear"])
api.add_output("y_17", ["log", "linear"])
api.add_output("y_18", ["log", "linear"])
api.add_output("y_19", ["log", "linear"])
api.add_output("y_20", ["log", "linear"])
# api.add_output("y_21", ["log", "linear"])
# api.add_output("y_22", ["log", "linear"])
# api.add_output("y_23", ["log", "linear"])
# api.add_output("y_24", ["log", "linear"])
# api.add_output("y_25", ["log", "linear"])

api.add_training_data(6300)
api.add_validation_data(700)

api.train(epochs=10000, batch_size=512, verbose=True)
api.plot_loss_history()

api.print_validation(use_log=True, print_table=False)
api.plot_validation(use_log=True)
api.export_validation()

api.save()
